-- MySQL Script generated by MySQL Workbench
<<<<<<< HEAD
-- Wed Nov  4 09:38:44 2020
=======
-- Tue Oct 27 22:34:42 2020
>>>>>>> origin/dev
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Database creation - Office Warriors
-- -----------------------------------------------------
<<<<<<< HEAD
DROP DATABASE `office_warriors`;
=======
>>>>>>> origin/dev
CREATE DATABASE IF NOT EXISTS `office_warriors`;
USE `office_warriors` ;

-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user` ;

CREATE TABLE IF NOT EXISTS `user` (
<<<<<<< HEAD
  `id` INT NOT NULL AUTO_INCREMENT,
=======
  `user_id` INT NOT NULL AUTO_INCREMENT,
>>>>>>> origin/dev
  `username` VARCHAR(80) NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(80) NULL,
  `is_admin` TINYINT NULL,
  `is_logged` TINYINT NULL,
<<<<<<< HEAD
  PRIMARY KEY (`id`))
=======
  PRIMARY KEY (`user_id`))
>>>>>>> origin/dev
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `game`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `game` ;

CREATE TABLE IF NOT EXISTS `game` (
<<<<<<< HEAD
  `id` INT NOT NULL AUTO_INCREMENT,
=======
  `game_id` INT NOT NULL AUTO_INCREMENT,
  `max_floor` INT NULL,
  `event_count` INT NULL,
  `save` DATETIME NULL,
  PRIMARY KEY (`game_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `character`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `character` ;

CREATE TABLE IF NOT EXISTS `character` (
  `character_id` INT NOT NULL AUTO_INCREMENT,
>>>>>>> origin/dev
  `name` VARCHAR(80) NULL,
  `image` VARCHAR(255) NULL,
  `strength` INT NULL,
  `energy` INT NULL,
  `humor` INT NULL,
  `agility` INT NULL,
<<<<<<< HEAD
  `max_floor` INT NULL,
  `event_count` INT NULL,
  `save` DATETIME NULL,
  `is_ended` TINYINT NULL DEFAULT 0,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `fk_Character_User_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_Character_User`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
=======
  `user_id` INT NOT NULL,
  `game_id` INT NOT NULL,
  PRIMARY KEY (`character_id`, `user_id`, `game_id`),
  INDEX `fk_Character_User_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_character_game1_idx` (`game_id` ASC) VISIBLE,
  CONSTRAINT `fk_Character_User`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_character_game1`
    FOREIGN KEY (`game_id`)
    REFERENCES `game` (`game_id`)
>>>>>>> origin/dev
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `item` ;

CREATE TABLE IF NOT EXISTS `item` (
<<<<<<< HEAD
  `id` INT NOT NULL AUTO_INCREMENT,
=======
  `item_id` INT NOT NULL AUTO_INCREMENT,
>>>>>>> origin/dev
  `name` VARCHAR(80) NULL,
  `image` VARCHAR(255) NULL,
  `strength` INT NULL,
  `energy` INT NULL,
  `humor` INT NULL,
  `agility` INT NULL,
<<<<<<< HEAD
  PRIMARY KEY (`id`))
=======
  PRIMARY KEY (`item_id`))
>>>>>>> origin/dev
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `event` ;

CREATE TABLE IF NOT EXISTS `event` (
<<<<<<< HEAD
  `id` INT NOT NULL AUTO_INCREMENT,
=======
  `event_id` INT NOT NULL AUTO_INCREMENT,
>>>>>>> origin/dev
  `name` VARCHAR(80) NULL,
  `image` VARCHAR(255) NULL,
  `description` MEDIUMTEXT NULL,
  `strength` INT NULL,
  `energy` INT NULL,
  `humor` INT NULL,
  `agility` INT NULL,
  `floor_restriction` INT NULL,
<<<<<<< HEAD
  PRIMARY KEY (`id`))
=======
  PRIMARY KEY (`event_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `game_has_event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `game_has_event` ;

CREATE TABLE IF NOT EXISTS `game_has_event` (
  `game_id` INT NOT NULL,
  `event_id` INT NOT NULL,
  PRIMARY KEY (`game_id`, `event_id`),
  INDEX `fk_game_has_event_event1_idx` (`event_id` ASC) VISIBLE,
  INDEX `fk_game_has_event_game1_idx` (`game_id` ASC) VISIBLE,
  CONSTRAINT `fk_game_has_event_game1`
    FOREIGN KEY (`game_id`)
    REFERENCES `game` (`game_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_game_has_event_event1`
    FOREIGN KEY (`event_id`)
    REFERENCES `event` (`event_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
>>>>>>> origin/dev
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `character_has_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `character_has_item` ;

CREATE TABLE IF NOT EXISTS `character_has_item` (
  `character_id` INT NOT NULL,
  `character_user_id` INT NOT NULL,
  `character_game_id` INT NOT NULL,
  `item_id` INT NOT NULL,
  PRIMARY KEY (`character_id`, `character_user_id`, `character_game_id`, `item_id`),
  INDEX `fk_character_has_item_item1_idx` (`item_id` ASC) VISIBLE,
  INDEX `fk_character_has_item_character1_idx` (`character_id` ASC, `character_user_id` ASC, `character_game_id` ASC) VISIBLE,
  CONSTRAINT `fk_character_has_item_character1`
<<<<<<< HEAD
    FOREIGN KEY (`character_id` , `character_user_id`)
    REFERENCES `game` (`id` , `user_id`)
=======
    FOREIGN KEY (`character_id` , `character_user_id` , `character_game_id`)
    REFERENCES `character` (`character_id` , `user_id` , `game_id`)
>>>>>>> origin/dev
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_character_has_item_item1`
    FOREIGN KEY (`item_id`)
<<<<<<< HEAD
    REFERENCES `item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `game_has_event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `game_has_event` ;

CREATE TABLE IF NOT EXISTS `game_has_event` (
  `game_id` INT NOT NULL,
  `game_user_id` INT NOT NULL,
  `event_id` INT NOT NULL,
  PRIMARY KEY (`game_id`, `game_user_id`, `event_id`),
  INDEX `fk_game_has_event_event1_idx` (`event_id` ASC) VISIBLE,
  INDEX `fk_game_has_event_game1_idx` (`game_id` ASC, `game_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_game_has_event_game1`
    FOREIGN KEY (`game_id` , `game_user_id`)
    REFERENCES `game` (`id` , `user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_game_has_event_event1`
    FOREIGN KEY (`event_id`)
    REFERENCES `event` (`id`)
=======
    REFERENCES `item` (`item_id`)
>>>>>>> origin/dev
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
